SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../../src/scrambler.v
TOPLEVEL = scrambler
MODULE = test_scrambler
include $(shell cocotb-config --makefiles)/Makefile.sim                                                          
